{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.annotations.certArn }}
    alb.ingress.kubernetes.io/group.name: "xr-demo-{{ .Values.ingress.annotations.albScheme }}"
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.albScheme }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: 200,302
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.annotations.dnsName }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.annotations.dnsName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: {{ .Values.grafana.service.port }}
{{- end }}