apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image }}
          ports:
            - containerPort: 9100
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9100
  selector:
    app: node-exporter
